server.port=8081
spring.application.name=rm-mock-api
management.endpoints.web.exposure.include=health,info
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs
rm.mock.projects=8
rm.mock.seed=42
